services:
  - type: web
    name: canvas-sync-web
    runtime: image
    repo: https://github.com/sidhesh77/CanvasSync
    branch: main
    dockerfilePath: ./apps/web/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_HTTP_URL
        value: https://canvas-sync-http-server.onrender.com/api/v1
      - key: NEXT_PUBLIC_WS_URL
        value: wss://canvas-sync-ws-server.onrender.com

  - type: web
    name: canvas-sync-http-server
    runtime: image
    repo: https://github.com/sidhesh77/CanvasSync
    branch: main
    dockerfilePath: ./apps/http-server/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: "4001"
      - key: FRONTEND_ORIGIN
        value: https://canvas-sync-web.onrender.com

  - type: web
    name: canvas-sync-ws-server
    runtime: image
    repo: https://github.com/sidhesh77/CanvasSync
    branch: main
    dockerfilePath: ./apps/ws-server/Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: "4002"
